# Add path
export PATH="$PATH:~/work/phtest/phtest"
export CSCOPE_DB="/home/hongli.yin/work/purity/cscope.out"

# show git branch in command prompt
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\033[31m\]\u@:\[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

# Source bash aliases file
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
