" Basics
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set number
set hlsearch
syntax on
set viminfo='20,<1000
cs add $CSCOPE_DB

" Indentation
filetype plugin indent on
autocmd FileType c,cpp set softtabstop=8 shiftwidth=8 expandtab
autocmd FileType python set softtabstop=4 shiftwidth=4 expandtab

" Width
set tw=100
set colorcolumn=101
highlight ColorColumn ctermbg=7
set formatoptions+=t

" Fold
set tags+=tags;/
hi Folded ctermbg=Black
set foldlevel=1
set foldmethod=manual
"set foldcolumn=2
"au BufWinLeave * mkview
"au BufWinEnter * silent loadview

" Status line
set laststatus=2
set statusline=
set statusline+=%<\                       " cut at start
set statusline+=%2*[%n%H%M%R%W]%*\        " flags and buf no
set statusline+=%-40f\                    " path
set statusline+=%=%1*%y%*%*\              " file type
set statusline+=%10((%l,%c)%)\            " line and column
set statusline+=%P                        " percentage of file

" Remember last position
if has("autocmd")
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Vundle begin
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
call vundle#end()            " required
" Vundle end

" YouCompleteMe
let g:ycm_confirm_extra_conf = 0
" Code navigation with Ctrl-] , use Ctrl-O to get back to previous location
nnoremap <silent> <C-]> :YcmCompleter GoTo<CR>

" Hight white space
"highlight ExtraWhitespace ctermbg=red guibg=red
"match ExtraWhitespace /\s\+$/
